# Site settings
title: Grep Giggles
email: grepgiggles@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Jekyll Theme Demo
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://grepgiggles.github.io" # the base hostname & protocol for your site
twitter_username: username
github_username: grepgiggles

# Build settings
# markdown: redcarpet
# markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
